In [1]:
%matplotlib tk
#%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings
import glob, os
import seaborn as sns
import matplotlib.ticker as plticker
import io
warnings.simplefilter("ignore")
plt.rcParams['figure.figsize'] = [15, 5]

In [2]:
#Load al Files, sort them and put them into dataframes

df001_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df002_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df003_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df004_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df005_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df006_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df007_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df008_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df009_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df010_surface = pd.read_csv('SimRNA_output/CopStems_surface_00_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint0_surface = pd.read_csv('SimRNA_output/CopStems_surface_00.csv_bp',sep="\t")
print (dfint0_surface)

    nr  bp1  bp2      count
0    0    2   51  365000284
1    1   64   93  442902131
2    2   69   89  356210306
3    3   17   36   80717624
4    4   17   35  422763352
..  ..  ...  ...        ...
76  76   16   37  167086335
77  77    0   53  384827230
78  78   14   38   33278128
79  79   25   80  446883494
80  80   70   87     346079

[81 rows x 4 columns]


In [3]:
df101_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df102_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df103_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df104_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df105_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df106_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df107_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df108_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df109_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df110_expand = pd.read_csv('SimRNA_output/CopStems_expand_01_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint1_expand = pd.read_csv('SimRNA_output/CopStems_expand_01.csv_bp',sep="\t")

In [4]:
df101_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df102_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df103_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df104_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df105_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df106_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df107_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df108_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df109_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df110_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint1_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01.csv_bp',sep="\t")

In [5]:
df101_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df102_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df103_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df104_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df105_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df106_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df107_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df108_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df109_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df110_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint1_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_01.csv_bp',sep="\t")

In [6]:
df201_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df202_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df203_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df204_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df205_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df206_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df207_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df208_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df209_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df210_expand = pd.read_csv('SimRNA_output/CopStems_expand_02_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint2_expand = pd.read_csv('SimRNA_output/CopStems_expand_02.csv_bp',sep="\t")

In [7]:
df201_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df202_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df203_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df204_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df205_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df206_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df207_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df208_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df209_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df210_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint2_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_01.csv_bp',sep="\t")

In [8]:
dfint2_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_02.interaction-csv',sep="\t")
df201_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df202_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df203_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df204_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df205_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df206_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df207_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df208_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df209_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df210_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint2_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_02.csv_bp',sep="\t")

In [9]:
df301_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df302_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df303_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df304_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df305_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df306_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df307_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df308_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df309_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df310_expand = pd.read_csv('SimRNA_output/CopStems_expand_03_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint3_expand = pd.read_csv('SimRNA_output/CopStems_expand_03.interaction-csv',sep="\t")

In [10]:
df301_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df302_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df303_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df304_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df305_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df306_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df307_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df308_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df309_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df310_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint3_expand00 = pd.read_csv('SimRNA_output/CopStems_expand_long00_03.csv_bp',sep="\t")

In [11]:
df301_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df302_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df303_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df304_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df305_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df306_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df307_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df308_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df309_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df310_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint3_expandsurface = pd.read_csv('SimRNA_output/CopStems_expand_surface_03.csv_bp',sep="\t")

In [12]:
df301_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df302_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df303_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df304_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df305_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df306_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df307_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df308_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df309_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df310_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint3_expandheavy = pd.read_csv('SimRNA_output/CopStemsHeavy_expand_03.csv_bp',sep="\t")

In [13]:
df01_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_01.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df02_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_02.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df03_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_03.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df04_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_04.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df05_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_05.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df06_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_06.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df07_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_07.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df08_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_08.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df09_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_09.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
df10_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04_10.csv_bp',sep="\t",skiprows=[i for i in range(1,3)])
dfint_8bp = pd.read_csv('SimRNA_output/CopStems8bp_surface_04.csv_bp',sep="\t")

In [14]:
bp8 = np.zeros(shape=(103,103))

for index, row in dfint_8bp.iterrows():
    bp8[row['bp1'],row['bp2']]= row['count']

print(bp8)

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0. 230. ...   0.   0.   0.]
 [  0. 216.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [60]:
seq= str('GGGCCCCGGUAAUCUUUUCGUACUCGCCAAAGUUGAAGAAGAUUAUCGGGGUUU CCCCGAUAAUCUUCUUCAACUUUGGCGAGUACGAAAAGAUUACCGGGG')
slist =list(seq)
chainbreak = seq.index(" ")
print ('Chainbreak: {}'.format(chainbreak))

ax = dfint0_surface.plot.hexbin(x='bp1',y='bp2', C='count', alpha=1,  gridsize=70, cmap="viridis")
  
xticklabels = slist
ax.set_xticks(np.arange(len(slist)))
ax.set_xticklabels(xticklabels)

yticklabels = slist
ax.set_yticks(np.arange(len(slist)))
ax.set_yticklabels(xticklabels)

ax.grid(axis='both',color='grey',linestyle='-', linewidth=0.5, alpha=0.2)

ax.set_aspect("equal")
ax.set_title("gridsize=100")
ax.axvline(x=chainbreak)
ax.axhline(y=chainbreak)

plt.show()

Chainbreak: 54


In [ ]:
#Set 
major_ticks = np.arange(1, len(slist), 10)
ax.set_xticks(major_ticks)
ax.set_yticks(major_ticks)

minor_ticks = np.arange(1,len(slist), 1)
ax.set_xticks(minor_ticks)
ax.set_yticks(minor_ticks)

    
xticklabels = slist
#ax.set_xticks(np.arange(len(slist)))
ax.set_xticklabels(xticklabels)

yticklabels = slist

#ax.set_yticks(np.arange(len(slist)))
ax.set_yticklabels(xticklabels)

ax.grid(which='minor',axis='both',color='grey',linestyle='--', linewidth=0.5, alpha=0.2)
ax.grid(which='major',axis='both',color='grey',linestyle='-', linewidth=0.5, alpha=0.5)




In [16]:

'''
fig, (ax, ax2) = plt.subplots(nrows=2)

#h1 = ax.hexbin(dfint_8bp.bp1, dfint_8bp.bp2, C=dfint_8bp.count, gridsize=100, cmap="copper")
#h2 = ax2.hexbin(dfint_8bp.bp1, dfint_8bp.bp2, C=dfint_8bp.count, gridsize=10, cmap="copper")

fig.colorbar(ax, ax=ax)
fig.colorbar(ax2, ax=ax2)
ax.set_aspect("equal")
ax2.set_aspect("equal")
ax.set_title("gridsize=100")
ax2.set_title("gridsize=10")
fig.subplots_adjust(hspace=0.3)
'''
'''
fig, ax = plt.subplots()
sc = ax.scatter(dfint_8bp.bp1, dfint_8bp.bp2, c=dfint_8bp.count,  cmap="copper")
h1 = ax.hexbin(df.v1, df.v2, C=df.yy, gridsize=100, cmap="copper")
fig.colorbar(sc, ax=ax)
ax.set_aspect("equal")

ax.scatter()

ax = plt.gca(dfint_8bp.bp1, dfint_8bp.bp2, dfint_8bp.count, cmap="copper")


ax1 = dfint_8bp.plot.scatter(x='bp1',y='bp2', c='count', alpha=1, color='cornflowerblue', ax=ax, label='00', cmap='copper')
ax1.set_xlabel('Interaction length', fontdict=None, labelpad=None)
ax1.set_ylabel('Energy', fontdict=None, labelpad=None)
ax.get_legend().remove()
plt.show()
'''
'''
symbol = ((np.asarray(dfint_8bp['nr'])).reshape(103,103))
perchange = ((np.asarray(dfint_8bp[])))

corr = np.corrcoef(np.random.randn(10, 200))
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True
with sns.axes_style("white"):
    ax = sns.heatmap(corr, mask=mask, vmax=.3, square=True,  cmap="YlGnBu")
    plt.show()

'''
'''
corr = np.corrcoef(np.random.randn(10, 200))
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True
with sns.axes_style("white"):
    ax = sns.heatmap(corr, mask=mask, vmax=.3, square=True,  cmap="YlGnBu")
    plt.show()
'''
'''
df = pd.read_clipboard()
table = dfint0_surface.pivot('bp1', 'bp2', 'count')
ax = sns.heatmap(table)
ax.invert_yaxis()
print(table)
plt.show()
'''

"\ndf = pd.read_clipboard()\ntable = dfint0_surface.pivot('bp1', 'bp2', 'count')\nax = sns.heatmap(table)\nax.invert_yaxis()\nprint(table)\nplt.show()\n"